Erikslud explore wicket bootstrap
tieto/WebWicker pull request #4
Opened 2017-02-13 14:44 UTC by erikslud

2017-02-13 14:54 UTC, erikslud commented
More bootstrap adjustment needed to get a robust and consistent "look and feel". This is just a first step.

2017-02-13 15:09 UTC, svebichr requested changes
I think you may have a bad autocrlf setting since all files you edited has been converted to crlf instead of the normalized lf. This makes it very difficult to review, it looks like everything is changed.

2017-02-13 15:09 UTC, svebichr commented on WebWickerCore/src/main/java/com/tieto/webwicker/web/HomePage.html
> +					<li>
Duplicate li element.

2017-02-14 07:40 UTC, svebichr commented on WebWickerEiffel/src/main/java/com/tieto/webwicker/eiffel/web/commits/CommitPage.java
> +	private static final List<String> notVerified = Arrays.asList(new String[]{"INCONCLUSIVE"});
Shouldn't it be INCONCLUSIVE and FAILURE? Or can FAILURE never occur for verified?

2017-02-16 15:25 UTC, merged